### ISSUE TITLE
Feature req: allow to check a TCP port

### ISSUE THREAD

**Issue by riddle** [mostro/mostro#7]
Example: checking `25565` port to see if it responds or if it’s not used. In a sense, this can notify if a process using it goes down.

**Comment by arnaudl** [comment]
There is a new script called `tcp.sh` that checks that a TCP port responds, and reports the connection time.

Usage:

* `RUN tcp.sh 80` will connect to localhost, on the port 80
* `RUN tcp.sh -h www.mostro.com 80` will connect to www.mostro.com, on the port 80
* `RUN tcp.sh -t 10 -h www.mostro.com 80` will connect to www.mostro.com, on the port 80, with a timeout of 10 seconds (default: 5 seconds)
